# Generated by Django 6.0.6 on 2026-07-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_info_locked',
            field=models.BooleanField(default=False, help_text='Set to True once employee has personally filled phone, address and profile picture. Admin cannot override these fields once locked.'),
        ),
    ]
